spring:
  datasource:
    username:  root
    password:  266700
    url: jdbc:mysql://localhost:3306/wangwork?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.wys.work.entity
  mapper-locations: classpath:mapper/*.xml